[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
dyn-clone = "1.0.10"
easybench = "1.1.0"
thiserror = "1.0.39"
